name: diff

on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - '.pre-commit-config.yaml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1

jobs:
  diff:
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      - name: CDK Diff Check
        run: |
          source .venv/bin/activate
          cdk diff -c base_url="${{ secrets.BASE_URL }}"
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
